.TH "BASIC256" "1" "January 31, 2008" "Ryan Kavanagh" ""
.SH "NAME"
BASIC256 \- Educational BASIC programming environment for children 
.SH "SYNOPSIS"
.B basic256
.br 
.SH "DESCRIPTION"
basic256 is an easy to use version of BASIC designed to teach young children
the basics of computer programming. 
.PP 
Features include:
 \- traditional control structures like gosub, for/next and goto
 \- built-in graphics and text mode
 \- set of detailed, easy-to-follow tutorials
 \- ... and more
.SH "WEBPAGE"
The basic256 website and tutorials can be found at http://kidbasic.sourceforge.net/
.SH "AUTHOR"
basic256 was written by Ian Larson <drblast@users.sourceforge.net>, Tony Dann
<supertony007@googlemail.com> and Ferry Hendrikx <ferry.hendrikx@gmail.com>.

.PP 
This manual page was written by Ryan Kavanagh <ryanakca@kubuntu.org>, for the
Debian and Ubuntu projects (but may be used by others).
